/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    If you even *think* about it, the engine will *know* and will come looking
    to devour your soul. You don't want to make it angry. Trust me.
===========================================================================*/
#if _MSC_VER
#pragma warning(disable:4121)
#elif defined PS3
#pragma ms_struct on
#endif
#pragma pack (push,4)

#ifndef UWINDOW_API
#define UWINDOW_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern UWINDOW_API FName UWINDOW_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(ShutdownAllDialogs)

#ifndef NAMES_ONLY


//***************************************************************************//
/*	\class UWindowConsole
*/
//***************************************************************************//

class UWINDOW_API UWindowConsole : public UConsole
{
public:
    class UUWindowRootWindow* Root;
    FStringNoInit RootWindow;
    FLOAT OldClipX;
    FLOAT OldClipY;
    FLOAT JoyX;
    FLOAT LastJoyX;
    FLOAT JoyY;
    FLOAT LastJoyY;
    FLOAT JoyRX;
    FLOAT LastJoyRX;
    FLOAT JoyRY;
    FLOAT LastJoyRY;
    class UClass* ConsoleClass;
    FLOAT MouseScale;
    BITFIELD ShowDesktop:1 GCC_PACK(4);
    BITFIELD bShowConsole:1;
    BITFIELD bConsoleLaunchedUWindow:1;
    BITFIELD bBlackout:1;
    BITFIELD bUWindowType:1;
    BITFIELD bUWindowActive:1;
    BITFIELD bQuickKeyEnable:1;
    BITFIELD bCloseForSureThisTime:1;
    BITFIELD bLevelChange:1;
    BITFIELD bDontDrawMouse:1;
    BITFIELD bMoveMouse:1;
    FStringNoInit OldLevel GCC_PACK(4);
    BYTE ConsoleKey;
    BYTE InGameWindowKey;
    BYTE UWindowKey;
    class UUWindowFramedWindow* ConsoleWindow;
    dnArray<FSMenuUnlock> KeyArray;
    BITFIELD bDisableLJoyInput:1 GCC_PACK(4);
    inline void __fastcall eventShutdownAllDialogs()
    {
        ProcessEvent(FindFunctionChecked(UWINDOW_ShutdownAllDialogs), NULL);
    }
    DECLARE_CLASS(UWindowConsole,UConsole,0|CLASS_Transient|CLASS_Config,UWindow)

    // properties that must be constructed special for UWindowConsole:
    //       * KeyArray

};
// Class WindowConsole exported:
//   Properties size: 104 bytes (1992 total)


//***************************************************************************//
/*	\class UUWindowBase
*/
//***************************************************************************//

class UWINDOW_API UUWindowBase : public UObject
{
public:
    DECLARE_CLASS(UUWindowBase,UObject,0,UWindow)
    NO_DEFAULT_CONSTRUCTOR(UUWindowBase)
};
// Class UWindowBase exported:
//   Properties size: 0 bytes (40 total)


//***************************************************************************//
/*	\class UUWindowWindow
*/
//***************************************************************************//

class UWINDOW_API UUWindowWindow : public UUWindowBase
{
public:
    FLOAT WinLeft;
    FLOAT WinTop;
    FLOAT WinWidth;
    FLOAT WinHeight;
    class UUWindowWindow* ParentWindow;
    class UUWindowWindow* FirstChildWindow;
    class UUWindowWindow* LastChildWindow;
    class UUWindowWindow* NextSiblingWindow;
    class UUWindowWindow* PrevSiblingWindow;
    class UUWindowWindow* ActiveWindow;
    class UUWindowRootWindow* Root;
    class UUWindowWindow* OwnerWindow;
    class UUWindowWindow* ModalWindow;
    BITFIELD bWindowVisible:1 GCC_PACK(4);
    BITFIELD bNoClip:1;
    BITFIELD bMouseDown:1;
    BITFIELD bRMouseDown:1;
    BITFIELD bMMouseDown:1;
    BITFIELD bAlwaysBehind:1;
    BITFIELD bAcceptsFocus:1;
    BITFIELD bAlwaysOnTop:1;
    BITFIELD bLeaveOnscreen:1;
    BITFIELD bUWindowActive:1;
    BITFIELD bTransient:1;
    BITFIELD bAcceptsHotKeys:1;
    BITFIELD bIgnoreLDoubleClick:1;
    BITFIELD bIgnoreMDoubleClick:1;
    BITFIELD bIgnoreRDoubleClick:1;
    FLOAT ClickTime GCC_PACK(4);
    FLOAT MClickTime;
    FLOAT RClickTime;
    FLOAT ClickX;
    FLOAT ClickY;
    FLOAT MClickX;
    FLOAT MClickY;
    FLOAT RClickX;
    FLOAT RClickY;
    FLOAT ClientAreaAlpha;
    class UUWindowLookAndFeel* LookAndFeel;
    FRegion ClippingRegion;
    FColor WhiteColor;
    FColor BlackColor;
    INT ResizeFrames;
    FMouseCursor cursor;
    class UUWindowWindow* ChildInFocus;
    BITFIELD bNavUpRepeatBlock:1 GCC_PACK(4);
    BITFIELD bNavDownRepeatBlock:1;
    BITFIELD bNavRightRepeatBlock:1;
    BITFIELD bNavLeftRepeatBlock:1;
    FLOAT NavRepeatTimeout GCC_PACK(4);
    FLOAT NavRepeatTime;
    FLOAT NavRepeatTimeHold;
    FSSoundInfo SoundNavigateInfo;
    DECLARE_FUNCTION(execClipText);
    DECLARE_FUNCTION(execDrawStretchedTextureSegment);
    DECLARE_CLASS(UUWindowWindow,UUWindowBase,0,UWindow)

    // properties that must be constructed special for UUWindowWindow:
    //       * SoundNavigateInfo

};
// Class UWindowWindow exported:
//   Properties size: 336 bytes (376 total)


//***************************************************************************//
/*	\class UUWindowRootWindow
*/
//***************************************************************************//

class UWINDOW_API UUWindowRootWindow : public UUWindowWindow
{
public:
    class UUWindowWindow* MouseWindow;
    BITFIELD bMouseCapture:1 GCC_PACK(4);
    FLOAT MouseX GCC_PACK(4);
    FLOAT MouseY;
    FLOAT OldMouseX;
    FLOAT OldMouseY;
    class UWindowConsole* Console;
    class UUWindowWindow* FocusedWindow;
    class UUWindowWindow* KeyFocusWindow;
    FMouseCursor NormalCursor;
    FMouseCursor MoveCursor;
    FMouseCursor DiagCursor1;
    FMouseCursor HandCursor;
    FMouseCursor HSplitCursor;
    FMouseCursor VSplitCursor;
    FMouseCursor DiagCursor2;
    FMouseCursor NSCursor;
    FMouseCursor WECursor;
    FMouseCursor WaitCursor;
    BITFIELD bQuickKeyEnable:1 GCC_PACK(4);
    class UUWindowHotkeyWindowList* HotkeyWindows GCC_PACK(4);
    FLOAT GUIScale;
    FLOAT RealWidth;
    FLOAT RealHeight;
    class UUWindowLookAndFeel* LooksAndFeels[20];
    FStringNoInit LookAndFeelClass;
    BITFIELD bRequestQuit:1 GCC_PACK(4);
    FLOAT QuitTime GCC_PACK(4);
    BITFIELD bAllowConsole:1 GCC_PACK(4);
    BITFIELD bAllowObjectives:1;
    BITFIELD DontCloseOnEscape:1;
    class UUWindowWindow* ScoreboardWindow GCC_PACK(4);
    BYTE WindowMode;
    DECLARE_CLASS(UUWindowRootWindow,UUWindowWindow,0|CLASS_Config,UWindow)
    NO_DEFAULT_CONSTRUCTOR(UUWindowRootWindow)
};
// Class UWindowRootWindow exported:
//   Properties size: 328 bytes (704 total)

#endif

AUTOGENERATE_FUNCTION(UUWindowWindow,-1,execClipText);
AUTOGENERATE_FUNCTION(UUWindowWindow,-1,execDrawStretchedTextureSegment);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#elif defined PS3
#pragma pack (pop)
#endif


#ifdef NATIVE_DEFS_ONLY
#if _MSC_VER
#pragma message("*** Including native definitions from UWindow.")
#endif
DECLARE_NATIVE_TYPE(UWindow,UUWindowWindow);
DECLARE_NATIVE_TYPE(UWindow,UUWindowBase);
DECLARE_NATIVE_TYPE(UWindow,UWindowConsole);
DECLARE_NATIVE_TYPE(UWindow,UUWindowRootWindow);

#define AUTO_INITIALIZE_REGISTRANTS_UWINDOW \
	UUWindowWindow::StaticClassNoInline(); \
	GNativeLookupFuncs[Lookup++] = &FindUWindowUUWindowWindowNative; \
	UUWindowBase::StaticClassNoInline(); \
	UWindowConsole::StaticClassNoInline(); \
	UUWindowRootWindow::StaticClassNoInline(); \

#endif // NATIVE_DEFS_ONLY

#ifdef NATIVES_ONLY
#if _MSC_VER
#pragma message("*** Including native classes from UWindow.")
#endif
NATIVE_INFO(UUWindowWindow) GUWindowUUWindowWindowNatives[] = 
{ 
	MAP_NATIVE(UUWindowWindow,execClipText)
	MAP_NATIVE(UUWindowWindow,execDrawStretchedTextureSegment)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(UWindow,UUWindowWindow);

#endif // NATIVES_ONLY
#if _MSC_VER
#pragma warning(default:4121)
#endif

#ifdef VERIFY_CLASS_SIZES
#pragma message("*** Verifying class sizes for UWindow.")
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,WinLeft)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,WinTop)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,WinWidth)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,WinHeight)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ParentWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,FirstChildWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,LastChildWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,NextSiblingWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,PrevSiblingWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ActiveWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,Root)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,OwnerWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ModalWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ClickTime)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,MClickTime)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,RClickTime)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ClickX)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ClickY)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,MClickX)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,MClickY)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,RClickX)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,RClickY)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ClientAreaAlpha)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,LookAndFeel)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ClippingRegion)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,WhiteColor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,BlackColor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ResizeFrames)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,cursor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,ChildInFocus)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,NavRepeatTimeout)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,NavRepeatTime)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,NavRepeatTimeHold)
VERIFY_CLASS_OFFSET_NODIE(UUWindowWindow,UWindowWindow,SoundNavigateInfo)
VERIFY_CLASS_SIZE_NODIE(UUWindowWindow)
VERIFY_CLASS_SIZE_NODIE(UUWindowBase)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,Root)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,RootWindow)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,OldClipX)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,OldClipY)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,JoyX)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,LastJoyX)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,JoyY)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,LastJoyY)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,JoyRX)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,LastJoyRX)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,JoyRY)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,LastJoyRY)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,ConsoleClass)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,MouseScale)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,OldLevel)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,ConsoleKey)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,InGameWindowKey)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,UWindowKey)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,ConsoleWindow)
VERIFY_CLASS_OFFSET_NODIE(UWindowConsole,WindowConsole,KeyArray)
VERIFY_CLASS_SIZE_NODIE(UWindowConsole)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,MouseWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,MouseX)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,MouseY)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,OldMouseX)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,OldMouseY)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,Console)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,FocusedWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,KeyFocusWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,NormalCursor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,MoveCursor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,DiagCursor1)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,HandCursor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,HSplitCursor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,VSplitCursor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,DiagCursor2)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,NSCursor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,WECursor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,WaitCursor)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,HotkeyWindows)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,GUIScale)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,RealWidth)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,RealHeight)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,LooksAndFeels)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,LookAndFeelClass)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,QuitTime)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,ScoreboardWindow)
VERIFY_CLASS_OFFSET_NODIE(UUWindowRootWindow,UWindowRootWindow,WindowMode)
VERIFY_CLASS_SIZE_NODIE(UUWindowRootWindow)
#endif // VERIFY_CLASS_SIZES
