/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    If you even *think* about it, the engine will *know* and will come looking
    to devour your soul. You don't want to make it angry. Trust me.
===========================================================================*/
#if _MSC_VER
#pragma warning(disable:4121)
#elif defined PS3
#pragma ms_struct on
#endif
#pragma pack (push,4)

#ifndef EDITOR_API
#define EDITOR_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern EDITOR_API FName EDITOR_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(Build)

#ifndef NAMES_ONLY


//***************************************************************************//
/*	\class UStaticMeshFactory
*/
//***************************************************************************//

class EDITOR_API UStaticMeshFactory : public UFactory
{
public:
    DECLARE_CLASS(UStaticMeshFactory,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UStaticMeshFactory)
};
// Class StaticMeshFactory exported:
//   Properties size: 0 bytes (104 total)


//***************************************************************************//
/*	\class UTextureFactory
*/
//***************************************************************************//

class EDITOR_API UTextureFactory : public UFactory
{
public:
    DECLARE_CLASS(UTextureFactory,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTextureFactory)
};
// Class TextureFactory exported:
//   Properties size: 0 bytes (104 total)


//***************************************************************************//
/*	\class UFontFactory
*/
//***************************************************************************//

class EDITOR_API UFontFactory : public UTextureFactory
{
public:
    DECLARE_CLASS(UFontFactory,UTextureFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UFontFactory)
};
// Class FontFactory exported:
//   Properties size: 0 bytes (104 total)


//***************************************************************************//
/*	\class UTrueTypeFontFactory
*/
//***************************************************************************//

class EDITOR_API UTrueTypeFontFactory : public UFontFactory
{
public:
    INT NumCharacters;
    INT VSize;
    INT USize;
    FLOAT Alpha;
    BITFIELD Resize:1 GCC_PACK(4);
    BITFIELD AntiAlias:1;
    BITFIELD Underline:1;
    BITFIELD Italic:1;
    BITFIELD Bold:1;
    INT FontSize GCC_PACK(4);
    FStringNoInit FontFile;
    DECLARE_CLASS(UTrueTypeFontFactory,UFontFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTrueTypeFontFactory)
};
// Class TrueTypeFontFactory exported:
//   Properties size: 52 bytes (156 total)


//***************************************************************************//
/*	\class UMusicFactory
*/
//***************************************************************************//

class EDITOR_API UMusicFactory : public UFactory
{
public:
    DECLARE_CLASS(UMusicFactory,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMusicFactory)
};
// Class MusicFactory exported:
//   Properties size: 0 bytes (104 total)


//***************************************************************************//
/*	\class USoundFactory
*/
//***************************************************************************//

class EDITOR_API USoundFactory : public UFactory
{
public:
    DECLARE_CLASS(USoundFactory,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(USoundFactory)
};
// Class SoundFactory exported:
//   Properties size: 0 bytes (104 total)


//***************************************************************************//
/*	\class UModelFactory
*/
//***************************************************************************//

class EDITOR_API UModelFactory : public UFactory
{
public:
    DECLARE_CLASS(UModelFactory,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UModelFactory)
};
// Class ModelFactory exported:
//   Properties size: 0 bytes (104 total)


//***************************************************************************//
/*	\class UPolysFactory
*/
//***************************************************************************//

class EDITOR_API UPolysFactory : public UFactory
{
public:
    DECLARE_CLASS(UPolysFactory,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UPolysFactory)
};
// Class PolysFactory exported:
//   Properties size: 0 bytes (104 total)


//***************************************************************************//
/*	\class ULevelFactory
*/
//***************************************************************************//

class EDITOR_API ULevelFactory : public UFactory
{
public:
    DECLARE_CLASS(ULevelFactory,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(ULevelFactory)
};
// Class LevelFactory exported:
//   Properties size: 0 bytes (104 total)


//***************************************************************************//
/*	\class UClassFactoryUC
*/
//***************************************************************************//

class EDITOR_API UClassFactoryUC : public UFactory
{
public:
    DECLARE_CLASS(UClassFactoryUC,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UClassFactoryUC)
};
// Class ClassFactoryUC exported:
//   Properties size: 0 bytes (104 total)


//***************************************************************************//
/*	\class UTextureFactoryNew
*/
//***************************************************************************//

class EDITOR_API UTextureFactoryNew : public UFactory
{
public:
    INT VSize;
    INT USize;
    class UClass* TextureClass;
    class UPackage* TexturePackage;
    FName TextureName;
    DECLARE_CLASS(UTextureFactoryNew,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTextureFactoryNew)
};
// Class TextureFactoryNew exported:
//   Properties size: 20 bytes (124 total)


//***************************************************************************//
/*	\class UClassFactoryNew
*/
//***************************************************************************//

class EDITOR_API UClassFactoryNew : public UFactory
{
public:
    class UClass* Superclass;
    class UPackage* ClassPackage;
    FName ClassName;
    DECLARE_CLASS(UClassFactoryNew,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UClassFactoryNew)
};
// Class ClassFactoryNew exported:
//   Properties size: 12 bytes (116 total)


//***************************************************************************//
/*	\class ULevelFactoryNew
*/
//***************************************************************************//

class EDITOR_API ULevelFactoryNew : public UFactory
{
public:
    BITFIELD CloseExistingWindows:1 GCC_PACK(4);
    FStringNoInit Author GCC_PACK(4);
    FStringNoInit LevelTitle;
    DECLARE_CLASS(ULevelFactoryNew,UFactory,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(ULevelFactoryNew)
};
// Class LevelFactoryNew exported:
//   Properties size: 28 bytes (132 total)


//***************************************************************************//
/*	\class UTextureCheckCommandlet
*/
//***************************************************************************//

class EDITOR_API UTextureCheckCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UTextureCheckCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTextureCheckCommandlet)
};
// Class TextureCheckCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UStripGoreCommandlet
*/
//***************************************************************************//

class EDITOR_API UStripGoreCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UStripGoreCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UStripGoreCommandlet)
};
// Class StripGoreCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class USoundPackCommandlet
*/
//***************************************************************************//

class EDITOR_API USoundPackCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(USoundPackCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(USoundPackCommandlet)
};
// Class SoundPackCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class USoundCheckCommandlet
*/
//***************************************************************************//

class EDITOR_API USoundCheckCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(USoundCheckCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(USoundCheckCommandlet)
};
// Class SoundCheckCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UOptimizeCommandlet
*/
//***************************************************************************//

class EDITOR_API UOptimizeCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UOptimizeCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptimizeCommandlet)
};
// Class OptimizeCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UMasterCommandlet
*/
//***************************************************************************//

class EDITOR_API UMasterCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UMasterCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMasterCommandlet)
};
// Class MasterCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UMakeCommandlet
*/
//***************************************************************************//

class EDITOR_API UMakeCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UMakeCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMakeCommandlet)
};
// Class MakeCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UKillUnrealCommandlet
*/
//***************************************************************************//

class EDITOR_API UKillUnrealCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UKillUnrealCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UKillUnrealCommandlet)
};
// Class KillUnrealCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UCoalesceLocCommandlet
*/
//***************************************************************************//

class EDITOR_API UCoalesceLocCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UCoalesceLocCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UCoalesceLocCommandlet)
};
// Class CoalesceLocCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UDumpIntCommandlet
*/
//***************************************************************************//

class EDITOR_API UDumpIntCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UDumpIntCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UDumpIntCommandlet)
};
// Class DumpIntCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UPrecacheIndexCommandlet
*/
//***************************************************************************//

class EDITOR_API UPrecacheIndexCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UPrecacheIndexCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UPrecacheIndexCommandlet)
};
// Class PrecacheIndexCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UMusicListCommandlet
*/
//***************************************************************************//

class EDITOR_API UMusicListCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UMusicListCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMusicListCommandlet)
};
// Class MusicListCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UAnimationListCommandlet
*/
//***************************************************************************//

class EDITOR_API UAnimationListCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UAnimationListCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UAnimationListCommandlet)
};
// Class AnimationListCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class USoundReferenceCommandlet
*/
//***************************************************************************//

class EDITOR_API USoundReferenceCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(USoundReferenceCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(USoundReferenceCommandlet)
};
// Class SoundReferenceCommandlet exported:
//   Properties size: 12 bytes (488 total)


//***************************************************************************//
/*	\class UObjectReferenceCommandlet
*/
//***************************************************************************//

class EDITOR_API UObjectReferenceCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UObjectReferenceCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UObjectReferenceCommandlet)
};
// Class ObjectReferenceCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UCutdownContentCommandlet
*/
//***************************************************************************//

class EDITOR_API UCutdownContentCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UCutdownContentCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UCutdownContentCommandlet)
};
// Class CutdownContentCommandlet exported:
//   Properties size: 24 bytes (500 total)


//***************************************************************************//
/*	\class UCookPlatformCommandlet
*/
//***************************************************************************//

class EDITOR_API UCookPlatformCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UCookPlatformCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UCookPlatformCommandlet)
};
// Class CookPlatformCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UMarkDLCMapsCommandlet
*/
//***************************************************************************//

class EDITOR_API UMarkDLCMapsCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UMarkDLCMapsCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMarkDLCMapsCommandlet)
};
// Class MarkDLCMapsCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UMarkDemoMapsCommandlet
*/
//***************************************************************************//

class EDITOR_API UMarkDemoMapsCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UMarkDemoMapsCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMarkDemoMapsCommandlet)
};
// Class MarkDemoMapsCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class ULinearPackagesCommandlet
*/
//***************************************************************************//

class EDITOR_API ULinearPackagesCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(ULinearPackagesCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(ULinearPackagesCommandlet)
};
// Class LinearPackagesCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UApplyPatchCommandlet
*/
//***************************************************************************//

class EDITOR_API UApplyPatchCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UApplyPatchCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UApplyPatchCommandlet)
};
// Class ApplyPatchCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UCreatePatchCommandlet
*/
//***************************************************************************//

class EDITOR_API UCreatePatchCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UCreatePatchCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UCreatePatchCommandlet)
};
// Class CreatePatchCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UMegaPackageCommandlet
*/
//***************************************************************************//

class EDITOR_API UMegaPackageCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UMegaPackageCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMegaPackageCommandlet)
};
// Class MegaPackageCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UCutdownCommandlet
*/
//***************************************************************************//

class EDITOR_API UCutdownCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UCutdownCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UCutdownCommandlet)
};
// Class CutdownCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UCompileMatCommandlet
*/
//***************************************************************************//

class EDITOR_API UCompileMatCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UCompileMatCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UCompileMatCommandlet)
};
// Class CompileMatCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class USMConvertCommandlet
*/
//***************************************************************************//

class EDITOR_API USMConvertCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(USMConvertCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(USMConvertCommandlet)
};
// Class SMConvertCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UTestCommandlet
*/
//***************************************************************************//

class EDITOR_API UTestCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UTestCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTestCommandlet)
};
// Class TestCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UMarkTexturesCommandlet
*/
//***************************************************************************//

class EDITOR_API UMarkTexturesCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UMarkTexturesCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMarkTexturesCommandlet)
};
// Class MarkTexturesCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UDataRipCommandlet
*/
//***************************************************************************//

class EDITOR_API UDataRipCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UDataRipCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UDataRipCommandlet)
};
// Class DataRipCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UPackageFlagCommandlet
*/
//***************************************************************************//

class EDITOR_API UPackageFlagCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UPackageFlagCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UPackageFlagCommandlet)
};
// Class PackageFlagCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UCheckUnicodeCommandlet
*/
//***************************************************************************//

class EDITOR_API UCheckUnicodeCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UCheckUnicodeCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UCheckUnicodeCommandlet)
};
// Class CheckUnicodeCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UDuke220ConvertCommandlet
*/
//***************************************************************************//

class EDITOR_API UDuke220ConvertCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UDuke220ConvertCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UDuke220ConvertCommandlet)
};
// Class Duke220ConvertCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UConformCommandlet
*/
//***************************************************************************//

class EDITOR_API UConformCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UConformCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UConformCommandlet)
};
// Class ConformCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UBuildSHACommandlet
*/
//***************************************************************************//

class EDITOR_API UBuildSHACommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UBuildSHACommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UBuildSHACommandlet)
};
// Class BuildSHACommandlet exported:
//   Properties size: 136 bytes (612 total)


//***************************************************************************//
/*	\class UBuildPatchLocCommandlet
*/
//***************************************************************************//

class EDITOR_API UBuildPatchLocCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UBuildPatchLocCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UBuildPatchLocCommandlet)
};
// Class BuildPatchLocCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UBuildMP3HashCommandlet
*/
//***************************************************************************//

class EDITOR_API UBuildMP3HashCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UBuildMP3HashCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UBuildMP3HashCommandlet)
};
// Class BuildMP3HashCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UBatchExportCommandlet
*/
//***************************************************************************//

class EDITOR_API UBatchExportCommandlet : public UCommandlet
{
public:
    DECLARE_CLASS(UBatchExportCommandlet,UCommandlet,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UBatchExportCommandlet)
};
// Class BatchExportCommandlet exported:
//   Properties size: 0 bytes (476 total)


//***************************************************************************//
/*	\class UBitArray
*/
//***************************************************************************//

class EDITOR_API UBitArray : public UObject
{
public:
    DECLARE_CLASS(UBitArray,UObject,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UBitArray)
};
// Class BitArray exported:
//   Properties size: 16 bytes (56 total)


//***************************************************************************//
/*	\class UBitMatrix
*/
//***************************************************************************//

class EDITOR_API UBitMatrix : public UBitArray
{
public:
    DECLARE_CLASS(UBitMatrix,UBitArray,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UBitMatrix)
};
// Class BitMatrix exported:
//   Properties size: 4 bytes (60 total)


//***************************************************************************//
/*	\class UTransactor
*/
//***************************************************************************//

class EDITOR_API UTransactor : public UObject
{
public:
    DECLARE_CLASS(UTransactor,UObject,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTransactor)
};
// Class Transactor exported:
//   Properties size: 0 bytes (40 total)


//***************************************************************************//
/*	\class UTransBuffer
*/
//***************************************************************************//

class EDITOR_API UTransBuffer : public UObject
{
public:
    DECLARE_CLASS(UTransBuffer,UObject,0|CLASS_Transient,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTransBuffer)
};
// Class TransBuffer exported:
//   Properties size: 40 bytes (80 total)


//***************************************************************************//
/*	\class UOptionsProxy
*/
//***************************************************************************//

class EDITOR_API UOptionsProxy : public UObject
{
public:
    FStringNoInit DlgCaption;
    INT WinWidth;
    INT WinHeight;
    DECLARE_CLASS(UOptionsProxy,UObject,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsProxy)
};
// Class OptionsProxy exported:
//   Properties size: 20 bytes (60 total)


//***************************************************************************//
/*	\class UOptionsStaticMeshSmooth
*/
//***************************************************************************//

enum EStaticMeshSmoothType
{
    ST_UnSmooth             =0,
    ST_SmoothAll            =1,
    ST_SmoothAngle          =2,
    ST_MAX                  =3,
};
class EDITOR_API UOptionsStaticMeshSmooth : public UOptionsProxy
{
public:
    /* EStaticMeshSmoothType */ BYTE SmoothType;
    FLOAT SmoothAngle;
    DECLARE_CLASS(UOptionsStaticMeshSmooth,UOptionsProxy,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsStaticMeshSmooth)
};
// Class OptionsStaticMeshSmooth exported:
//   Properties size: 8 bytes (68 total)


//***************************************************************************//
/*	\class UOptionsStaticMeshNormalMap
*/
//***************************************************************************//

enum ESuperSample
{
    SS_None                 =0,
    SS_2X                   =1,
    SS_4X                   =2,
    SS_8X                   =3,
    SS_MAX                  =4,
};
enum ESampleMode
{
    SAMPLE_CLOSEST          =0,
    SAMPLE_FARTHEST         =1,
    SAMPLE_FIRST_HIT        =2,
    SAMPLE_BEST_NORMAL      =3,
    SAMPLE_MAX              =4,
};
class EDITOR_API UOptionsStaticMeshNormalMap : public UOptionsProxy
{
public:
    BITFIELD bOverrideSize:1 GCC_PACK(4);
    INT OverrideWidth GCC_PACK(4);
    INT OverrideHeight;
    INT NumSmooths;
    INT NumExpands;
    BITFIELD bOverridePackage:1 GCC_PACK(4);
    FStringNoInit TexturePkg GCC_PACK(4);
    FStringNoInit TextureGroup;
    BITFIELD bAutoNumberNames:1 GCC_PACK(4);
    BITFIELD bAllowDistortion:1;
    BITFIELD bDebug:1;
    BITFIELD bDrawEdges:1;
    INT NumSamples GCC_PACK(4);
    FLOAT SampleScale;
    FLOAT SampleDist;
    /* ESampleMode */ BYTE SampleMode;
    /* ESuperSample */ BYTE SuperSample;
    FLOAT BumpScale;
    DECLARE_CLASS(UOptionsStaticMeshNormalMap,UOptionsProxy,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsStaticMeshNormalMap)
};
// Class OptionsStaticMeshNormalMap exported:
//   Properties size: 72 bytes (132 total)


//***************************************************************************//
/*	\class UOptionsMatNewStaticMesh
*/
//***************************************************************************//

class EDITOR_API UOptionsMatNewStaticMesh : public UOptionsProxy
{
public:
    FStringNoInit PkgName;
    FStringNoInit Group;
    FStringNoInit MeshName;
    FLOAT MeshPitch;
    FLOAT MeshYaw;
    FLOAT MeshRoll;
    DECLARE_CLASS(UOptionsMatNewStaticMesh,UOptionsProxy,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsMatNewStaticMesh)
};
// Class OptionsMatNewStaticMesh exported:
//   Properties size: 48 bytes (108 total)


//***************************************************************************//
/*	\class UOptionsSurfBevel
*/
//***************************************************************************//

class EDITOR_API UOptionsSurfBevel : public UOptionsProxy
{
public:
    INT Depth;
    INT Bevel;
    DECLARE_CLASS(UOptionsSurfBevel,UOptionsProxy,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsSurfBevel)
};
// Class OptionsSurfBevel exported:
//   Properties size: 8 bytes (68 total)


//***************************************************************************//
/*	\class UOptions2DShaperBezierDetail
*/
//***************************************************************************//

class EDITOR_API UOptions2DShaperBezierDetail : public UOptionsProxy
{
public:
    INT DetailLevel;
    DECLARE_CLASS(UOptions2DShaperBezierDetail,UOptionsProxy,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperBezierDetail)
};
// Class Options2DShaperBezierDetail exported:
//   Properties size: 4 bytes (64 total)


//***************************************************************************//
/*	\class UOptions2DShaper
*/
//***************************************************************************//

enum EAxis
{
    AXIS_X                  =0,
    AXIS_Y                  =1,
    AXIS_Z                  =2,
    AXIS_MAX                =3,
};
class EDITOR_API UOptions2DShaper : public UOptionsProxy
{
public:
    /* EAxis */ BYTE Axis;
    DECLARE_CLASS(UOptions2DShaper,UOptionsProxy,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaper)
};
// Class Options2DShaper exported:
//   Properties size: 4 bytes (64 total)


//***************************************************************************//
/*	\class UOptions2DShaperRevolve
*/
//***************************************************************************//

class EDITOR_API UOptions2DShaperRevolve : public UOptions2DShaper
{
public:
    INT Per360;
    INT Use;
    DECLARE_CLASS(UOptions2DShaperRevolve,UOptions2DShaper,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperRevolve)
};
// Class Options2DShaperRevolve exported:
//   Properties size: 8 bytes (72 total)


//***************************************************************************//
/*	\class UOptions2DShaperSheet
*/
//***************************************************************************//

class EDITOR_API UOptions2DShaperSheet : public UOptions2DShaper
{
public:
    DECLARE_CLASS(UOptions2DShaperSheet,UOptions2DShaper,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperSheet)
};
// Class Options2DShaperSheet exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UOptions2DShaperExtrudeToBevel
*/
//***************************************************************************//

class EDITOR_API UOptions2DShaperExtrudeToBevel : public UOptions2DShaper
{
public:
    FLOAT Height;
    FLOAT CapHeight;
    DECLARE_CLASS(UOptions2DShaperExtrudeToBevel,UOptions2DShaper,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperExtrudeToBevel)
};
// Class Options2DShaperExtrudeToBevel exported:
//   Properties size: 8 bytes (72 total)


//***************************************************************************//
/*	\class UOptions2DShaperExtrudeToPoint
*/
//***************************************************************************//

class EDITOR_API UOptions2DShaperExtrudeToPoint : public UOptions2DShaper
{
public:
    FLOAT Depth;
    DECLARE_CLASS(UOptions2DShaperExtrudeToPoint,UOptions2DShaper,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperExtrudeToPoint)
};
// Class Options2DShaperExtrudeToPoint exported:
//   Properties size: 4 bytes (68 total)


//***************************************************************************//
/*	\class UOptions2DShaperExtrude
*/
//***************************************************************************//

class EDITOR_API UOptions2DShaperExtrude : public UOptions2DShaper
{
public:
    FLOAT Depth;
    DECLARE_CLASS(UOptions2DShaperExtrude,UOptions2DShaper,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperExtrude)
};
// Class Options2DShaperExtrude exported:
//   Properties size: 4 bytes (68 total)


//***************************************************************************//
/*	\class UOptionsTexAlign
*/
//***************************************************************************//

enum ETAxis
{
    TAXIS_X                 =0,
    TAXIS_Y                 =1,
    TAXIS_Z                 =2,
    TAXIS_AUTO              =3,
    TAXIS_WALLS             =4,
    TAXIS_MAX               =5,
};
class EDITOR_API UOptionsTexAlign : public UOptionsProxy
{
public:
    /* ETAxis */ BYTE TAxis;
    DECLARE_CLASS(UOptionsTexAlign,UOptionsProxy,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsTexAlign)
};
// Class OptionsTexAlign exported:
//   Properties size: 4 bytes (64 total)


//***************************************************************************//
/*	\class UOptionsTexAlignCylinder
*/
//***************************************************************************//

class EDITOR_API UOptionsTexAlignCylinder : public UOptionsTexAlign
{
public:
    INT UTile;
    INT VTile;
    DECLARE_CLASS(UOptionsTexAlignCylinder,UOptionsTexAlign,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsTexAlignCylinder)
};
// Class OptionsTexAlignCylinder exported:
//   Properties size: 8 bytes (72 total)


//***************************************************************************//
/*	\class UOptionsTexAlignPlanar
*/
//***************************************************************************//

class EDITOR_API UOptionsTexAlignPlanar : public UOptionsTexAlign
{
public:
    DECLARE_CLASS(UOptionsTexAlignPlanar,UOptionsTexAlign,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsTexAlignPlanar)
};
// Class OptionsTexAlignPlanar exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UOptionsTexAlignFace
*/
//***************************************************************************//

class EDITOR_API UOptionsTexAlignFace : public UOptionsProxy
{
public:
    FLOAT TileU;
    FLOAT TileV;
    DECLARE_CLASS(UOptionsTexAlignFace,UOptionsProxy,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsTexAlignFace)
};
// Class OptionsTexAlignFace exported:
//   Properties size: 8 bytes (68 total)


//***************************************************************************//
/*	\class UOptionsBrushScale
*/
//***************************************************************************//

class EDITOR_API UOptionsBrushScale : public UOptionsProxy
{
public:
    FLOAT X;
    FLOAT Y;
    FLOAT Z;
    DECLARE_CLASS(UOptionsBrushScale,UOptionsProxy,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UOptionsBrushScale)
};
// Class OptionsBrushScale exported:
//   Properties size: 12 bytes (72 total)


//***************************************************************************//
/*	\class UTextureExporterTXT
*/
//***************************************************************************//

class EDITOR_API UTextureExporterTXT : public UExporter
{
public:
    DECLARE_CLASS(UTextureExporterTXT,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTextureExporterTXT)
};
// Class TextureExporterTXT exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UTextureExporterTGA
*/
//***************************************************************************//

class EDITOR_API UTextureExporterTGA : public UExporter
{
public:
    DECLARE_CLASS(UTextureExporterTGA,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTextureExporterTGA)
};
// Class TextureExporterTGA exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UTextureExporterBMP
*/
//***************************************************************************//

class EDITOR_API UTextureExporterBMP : public UExporter
{
public:
    DECLARE_CLASS(UTextureExporterBMP,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTextureExporterBMP)
};
// Class TextureExporterBMP exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UTextureExporterPCX
*/
//***************************************************************************//

class EDITOR_API UTextureExporterPCX : public UExporter
{
public:
    DECLARE_CLASS(UTextureExporterPCX,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTextureExporterPCX)
};
// Class TextureExporterPCX exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UClassExporterH
*/
//***************************************************************************//

class EDITOR_API UClassExporterH : public UExporter
{
public:
    DECLARE_CLASS(UClassExporterH,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UClassExporterH)
};
// Class ClassExporterH exported:
//   Properties size: 512 bytes (576 total)


//***************************************************************************//
/*	\class ULevelExporterDBD
*/
//***************************************************************************//

class EDITOR_API ULevelExporterDBD : public UExporter
{
public:
    DECLARE_CLASS(ULevelExporterDBD,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(ULevelExporterDBD)
};
// Class LevelExporterDBD exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class ULevelExporterMA
*/
//***************************************************************************//

class EDITOR_API ULevelExporterMA : public UExporter
{
public:
    DECLARE_CLASS(ULevelExporterMA,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(ULevelExporterMA)
};
// Class LevelExporterMA exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class ULevelExporterDXF
*/
//***************************************************************************//

class EDITOR_API ULevelExporterDXF : public UExporter
{
public:
    DECLARE_CLASS(ULevelExporterDXF,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(ULevelExporterDXF)
};
// Class LevelExporterDXF exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class ULevelExporterSTL
*/
//***************************************************************************//

class EDITOR_API ULevelExporterSTL : public UExporter
{
public:
    DECLARE_CLASS(ULevelExporterSTL,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(ULevelExporterSTL)
};
// Class LevelExporterSTL exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class ULevelExporterT3D
*/
//***************************************************************************//

class EDITOR_API ULevelExporterT3D : public UExporter
{
public:
    DECLARE_CLASS(ULevelExporterT3D,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(ULevelExporterT3D)
};
// Class LevelExporterT3D exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UModelExporterT3D
*/
//***************************************************************************//

class EDITOR_API UModelExporterT3D : public UExporter
{
public:
    DECLARE_CLASS(UModelExporterT3D,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UModelExporterT3D)
};
// Class ModelExporterT3D exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UPolysExporterT3D
*/
//***************************************************************************//

class EDITOR_API UPolysExporterT3D : public UExporter
{
public:
    DECLARE_CLASS(UPolysExporterT3D,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UPolysExporterT3D)
};
// Class PolysExporterT3D exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UClassExporterUC
*/
//***************************************************************************//

class EDITOR_API UClassExporterUC : public UExporter
{
public:
    DECLARE_CLASS(UClassExporterUC,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UClassExporterUC)
};
// Class ClassExporterUC exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UClassExporterUCH
*/
//***************************************************************************//

class EDITOR_API UClassExporterUCH : public UExporter
{
public:
    DECLARE_CLASS(UClassExporterUCH,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UClassExporterUCH)
};
// Class ClassExporterUCH exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UMusicExporterTracker
*/
//***************************************************************************//

class EDITOR_API UMusicExporterTracker : public UExporter
{
public:
    DECLARE_CLASS(UMusicExporterTracker,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMusicExporterTracker)
};
// Class MusicExporterTracker exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class USoundExporterWAV
*/
//***************************************************************************//

class EDITOR_API USoundExporterWAV : public UExporter
{
public:
    DECLARE_CLASS(USoundExporterWAV,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(USoundExporterWAV)
};
// Class SoundExporterWAV exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UTextBufferExporterTXT
*/
//***************************************************************************//

class EDITOR_API UTextBufferExporterTXT : public UExporter
{
public:
    DECLARE_CLASS(UTextBufferExporterTXT,UExporter,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UTextBufferExporterTXT)
};
// Class TextBufferExporterTXT exported:
//   Properties size: 0 bytes (64 total)


//***************************************************************************//
/*	\class UBrushBuilder
*/
//***************************************************************************//

struct EDITOR_API FBuilderPoly
{
    dnArray<INT> VertexIndices;
    INT Direction;
    FName Item;
    INT PolyFlags;

    FBuilderPoly() { }
    FBuilderPoly(ENoInit) : VertexIndices(E_NoInit) { }
};


struct UBrushBuilder_eventBuild_Parms
{
    BITFIELD ReturnValue;
};
class EDITOR_API UBrushBuilder : public UObject
{
public:
    FStringNoInit BitmapFilename;
    FStringNoInit ToolTip;
    dnArray<FVector> Vertices;
    dnArray<FBuilderPoly> Polys;
    FName Group;
    BITFIELD MergeCoplanars:1 GCC_PACK(4);
    DECLARE_FUNCTION(execPolyEnd);
    DECLARE_FUNCTION(execPolyi);
    DECLARE_FUNCTION(execPolyBegin);
    DECLARE_FUNCTION(execPoly4i);
    DECLARE_FUNCTION(execPoly3i);
    DECLARE_FUNCTION(execVertex3f);
    DECLARE_FUNCTION(execVertexv);
    DECLARE_FUNCTION(execBadParameters);
    DECLARE_FUNCTION(execGetPolyCount);
    DECLARE_FUNCTION(execGetVertex);
    DECLARE_FUNCTION(execGetVertexCount);
    DECLARE_FUNCTION(execEndBrush);
    DECLARE_FUNCTION(execBeginBrush);
    inline BITFIELD __fastcall eventBuild()
    {
        UBrushBuilder_eventBuild_Parms Parms;
        Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(EDITOR_Build), &Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UBrushBuilder,UObject,0,Editor)
    NO_DEFAULT_CONSTRUCTOR_START(UBrushBuilder)
    NO_DEFAULT_CONSTRUCTOR_INIT(Vertices)
    NO_DEFAULT_CONSTRUCTOR_INITLAST(Polys)
};
// Class BrushBuilder exported:
//   Properties size: 56 bytes (96 total)


//***************************************************************************//
/*	\class AEditorMesh
*/
//***************************************************************************//

class EDITOR_API AEditorMesh : public ARenderActor
{
public:
    BITFIELD bPaused:1 GCC_PACK(4);
    BITFIELD bUseMovementBone:1;
    BITFIELD bDrawMesh:1;
    BITFIELD bDrawSkeleton:1;
    BITFIELD bPersist:1;
    INT NumTextures GCC_PACK(4);
    INT TextureMemoryUsage;
    DECLARE_CLASS(AEditorMesh,ARenderActor,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(AEditorMesh)
};
// Class EditorMesh exported:
//   Properties size: 12 bytes (1680 total)

#endif

AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyEnd);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyi);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyBegin);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly4i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly3i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertex3f);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertexv);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBadParameters);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetPolyCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertex);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertexCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execEndBrush);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBeginBrush);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#elif defined PS3
#pragma pack (pop)
#endif


#ifdef NATIVE_DEFS_ONLY
#if _MSC_VER
#pragma message("*** Including native definitions from Editor.")
#endif
DECLARE_NATIVE_TYPE(Editor,UTextureCheckCommandlet);
DECLARE_NATIVE_TYPE(Editor,UStripGoreCommandlet);
DECLARE_NATIVE_TYPE(Editor,UStaticMeshFactory);
DECLARE_NATIVE_TYPE(Editor,USoundPackCommandlet);
DECLARE_NATIVE_TYPE(Editor,USoundCheckCommandlet);
DECLARE_NATIVE_TYPE(Editor,UOptimizeCommandlet);
DECLARE_NATIVE_TYPE(Editor,UBitMatrix);
DECLARE_NATIVE_TYPE(Editor,UBitArray);
DECLARE_NATIVE_TYPE(Editor,UTransactor);
DECLARE_NATIVE_TYPE(Editor,UTransBuffer);
DECLARE_NATIVE_TYPE(Editor,UOptionsStaticMeshSmooth);
DECLARE_NATIVE_TYPE(Editor,UOptionsProxy);
DECLARE_NATIVE_TYPE(Editor,UOptionsStaticMeshNormalMap);
DECLARE_NATIVE_TYPE(Editor,UOptionsMatNewStaticMesh);
DECLARE_NATIVE_TYPE(Editor,UOptionsSurfBevel);
DECLARE_NATIVE_TYPE(Editor,UOptions2DShaperBezierDetail);
DECLARE_NATIVE_TYPE(Editor,UOptions2DShaperRevolve);
DECLARE_NATIVE_TYPE(Editor,UOptions2DShaper);
DECLARE_NATIVE_TYPE(Editor,UOptions2DShaperSheet);
DECLARE_NATIVE_TYPE(Editor,UOptions2DShaperExtrudeToBevel);
DECLARE_NATIVE_TYPE(Editor,UOptions2DShaperExtrudeToPoint);
DECLARE_NATIVE_TYPE(Editor,UOptions2DShaperExtrude);
DECLARE_NATIVE_TYPE(Editor,UOptionsTexAlignCylinder);
DECLARE_NATIVE_TYPE(Editor,UOptionsTexAlign);
DECLARE_NATIVE_TYPE(Editor,UOptionsTexAlignPlanar);
DECLARE_NATIVE_TYPE(Editor,UOptionsTexAlignFace);
DECLARE_NATIVE_TYPE(Editor,UOptionsBrushScale);
DECLARE_NATIVE_TYPE(Editor,UFontFactory);
DECLARE_NATIVE_TYPE(Editor,UTextureFactory);
DECLARE_NATIVE_TYPE(Editor,UTextureExporterTXT);
DECLARE_NATIVE_TYPE(Editor,UTextureExporterTGA);
DECLARE_NATIVE_TYPE(Editor,UTextureExporterBMP);
DECLARE_NATIVE_TYPE(Editor,UTextureExporterPCX);
DECLARE_NATIVE_TYPE(Editor,UMusicFactory);
DECLARE_NATIVE_TYPE(Editor,USoundFactory);
DECLARE_NATIVE_TYPE(Editor,UModelFactory);
DECLARE_NATIVE_TYPE(Editor,UPolysFactory);
DECLARE_NATIVE_TYPE(Editor,ULevelFactory);
DECLARE_NATIVE_TYPE(Editor,UClassFactoryUC);
DECLARE_NATIVE_TYPE(Editor,UTextureFactoryNew);
DECLARE_NATIVE_TYPE(Editor,UClassFactoryNew);
DECLARE_NATIVE_TYPE(Editor,ULevelFactoryNew);
DECLARE_NATIVE_TYPE(Editor,UClassExporterH);
DECLARE_NATIVE_TYPE(Editor,ULevelExporterDBD);
DECLARE_NATIVE_TYPE(Editor,ULevelExporterMA);
DECLARE_NATIVE_TYPE(Editor,ULevelExporterDXF);
DECLARE_NATIVE_TYPE(Editor,ULevelExporterSTL);
DECLARE_NATIVE_TYPE(Editor,ULevelExporterT3D);
DECLARE_NATIVE_TYPE(Editor,UModelExporterT3D);
DECLARE_NATIVE_TYPE(Editor,UPolysExporterT3D);
DECLARE_NATIVE_TYPE(Editor,UClassExporterUC);
DECLARE_NATIVE_TYPE(Editor,UClassExporterUCH);
DECLARE_NATIVE_TYPE(Editor,UMusicExporterTracker);
DECLARE_NATIVE_TYPE(Editor,USoundExporterWAV);
DECLARE_NATIVE_TYPE(Editor,UTextBufferExporterTXT);
DECLARE_NATIVE_TYPE(Editor,UMasterCommandlet);
DECLARE_NATIVE_TYPE(Editor,UMakeCommandlet);
DECLARE_NATIVE_TYPE(Editor,UKillUnrealCommandlet);
DECLARE_NATIVE_TYPE(Editor,UCoalesceLocCommandlet);
DECLARE_NATIVE_TYPE(Editor,UDumpIntCommandlet);
DECLARE_NATIVE_TYPE(Editor,UPrecacheIndexCommandlet);
DECLARE_NATIVE_TYPE(Editor,UMusicListCommandlet);
DECLARE_NATIVE_TYPE(Editor,UAnimationListCommandlet);
DECLARE_NATIVE_TYPE(Editor,USoundReferenceCommandlet);
DECLARE_NATIVE_TYPE(Editor,UObjectReferenceCommandlet);
DECLARE_NATIVE_TYPE(Editor,UCutdownContentCommandlet);
DECLARE_NATIVE_TYPE(Editor,UCookPlatformCommandlet);
DECLARE_NATIVE_TYPE(Editor,UMarkDLCMapsCommandlet);
DECLARE_NATIVE_TYPE(Editor,UMarkDemoMapsCommandlet);
DECLARE_NATIVE_TYPE(Editor,ULinearPackagesCommandlet);
DECLARE_NATIVE_TYPE(Editor,UApplyPatchCommandlet);
DECLARE_NATIVE_TYPE(Editor,UCreatePatchCommandlet);
DECLARE_NATIVE_TYPE(Editor,UMegaPackageCommandlet);
DECLARE_NATIVE_TYPE(Editor,UCutdownCommandlet);
DECLARE_NATIVE_TYPE(Editor,UCompileMatCommandlet);
DECLARE_NATIVE_TYPE(Editor,USMConvertCommandlet);
DECLARE_NATIVE_TYPE(Editor,UTestCommandlet);
DECLARE_NATIVE_TYPE(Editor,UMarkTexturesCommandlet);
DECLARE_NATIVE_TYPE(Editor,UDataRipCommandlet);
DECLARE_NATIVE_TYPE(Editor,UPackageFlagCommandlet);
DECLARE_NATIVE_TYPE(Editor,UCheckUnicodeCommandlet);
DECLARE_NATIVE_TYPE(Editor,UDuke220ConvertCommandlet);
DECLARE_NATIVE_TYPE(Editor,UConformCommandlet);
DECLARE_NATIVE_TYPE(Editor,UBuildSHACommandlet);
DECLARE_NATIVE_TYPE(Editor,UBuildPatchLocCommandlet);
DECLARE_NATIVE_TYPE(Editor,UBuildMP3HashCommandlet);
DECLARE_NATIVE_TYPE(Editor,UBrushBuilder);
DECLARE_NATIVE_TYPE(Editor,UBatchExportCommandlet);
DECLARE_NATIVE_TYPE(Editor,UTrueTypeFontFactory);
DECLARE_NATIVE_TYPE(Editor,AEditorMesh);

#define AUTO_INITIALIZE_REGISTRANTS_EDITOR \
	UTextureCheckCommandlet::StaticClassNoInline(); \
	UStripGoreCommandlet::StaticClassNoInline(); \
	UStaticMeshFactory::StaticClassNoInline(); \
	USoundPackCommandlet::StaticClassNoInline(); \
	USoundCheckCommandlet::StaticClassNoInline(); \
	UOptimizeCommandlet::StaticClassNoInline(); \
	UBitMatrix::StaticClassNoInline(); \
	UBitArray::StaticClassNoInline(); \
	UTransactor::StaticClassNoInline(); \
	UTransBuffer::StaticClassNoInline(); \
	UOptionsStaticMeshSmooth::StaticClassNoInline(); \
	UOptionsProxy::StaticClassNoInline(); \
	UOptionsStaticMeshNormalMap::StaticClassNoInline(); \
	UOptionsMatNewStaticMesh::StaticClassNoInline(); \
	UOptionsSurfBevel::StaticClassNoInline(); \
	UOptions2DShaperBezierDetail::StaticClassNoInline(); \
	UOptions2DShaperRevolve::StaticClassNoInline(); \
	UOptions2DShaper::StaticClassNoInline(); \
	UOptions2DShaperSheet::StaticClassNoInline(); \
	UOptions2DShaperExtrudeToBevel::StaticClassNoInline(); \
	UOptions2DShaperExtrudeToPoint::StaticClassNoInline(); \
	UOptions2DShaperExtrude::StaticClassNoInline(); \
	UOptionsTexAlignCylinder::StaticClassNoInline(); \
	UOptionsTexAlign::StaticClassNoInline(); \
	UOptionsTexAlignPlanar::StaticClassNoInline(); \
	UOptionsTexAlignFace::StaticClassNoInline(); \
	UOptionsBrushScale::StaticClassNoInline(); \
	UEditorEngine::StaticClassNoInline(); \
	UFontFactory::StaticClassNoInline(); \
	UTextureFactory::StaticClassNoInline(); \
	UTextureExporterTXT::StaticClassNoInline(); \
	UTextureExporterTGA::StaticClassNoInline(); \
	UTextureExporterBMP::StaticClassNoInline(); \
	UTextureExporterPCX::StaticClassNoInline(); \
	UMusicFactory::StaticClassNoInline(); \
	USoundFactory::StaticClassNoInline(); \
	UModelFactory::StaticClassNoInline(); \
	UPolysFactory::StaticClassNoInline(); \
	ULevelFactory::StaticClassNoInline(); \
	UClassFactoryUC::StaticClassNoInline(); \
	UTextureFactoryNew::StaticClassNoInline(); \
	UClassFactoryNew::StaticClassNoInline(); \
	ULevelFactoryNew::StaticClassNoInline(); \
	UClassExporterH::StaticClassNoInline(); \
	ULevelExporterDBD::StaticClassNoInline(); \
	ULevelExporterMA::StaticClassNoInline(); \
	ULevelExporterDXF::StaticClassNoInline(); \
	ULevelExporterSTL::StaticClassNoInline(); \
	ULevelExporterT3D::StaticClassNoInline(); \
	UModelExporterT3D::StaticClassNoInline(); \
	UPolysExporterT3D::StaticClassNoInline(); \
	UClassExporterUC::StaticClassNoInline(); \
	UClassExporterUCH::StaticClassNoInline(); \
	UMusicExporterTracker::StaticClassNoInline(); \
	USoundExporterWAV::StaticClassNoInline(); \
	UTextBufferExporterTXT::StaticClassNoInline(); \
	UMasterCommandlet::StaticClassNoInline(); \
	UMakeCommandlet::StaticClassNoInline(); \
	UKillUnrealCommandlet::StaticClassNoInline(); \
	UCoalesceLocCommandlet::StaticClassNoInline(); \
	UDumpIntCommandlet::StaticClassNoInline(); \
	UPrecacheIndexCommandlet::StaticClassNoInline(); \
	UMusicListCommandlet::StaticClassNoInline(); \
	UAnimationListCommandlet::StaticClassNoInline(); \
	USoundReferenceCommandlet::StaticClassNoInline(); \
	UObjectReferenceCommandlet::StaticClassNoInline(); \
	UCutdownContentCommandlet::StaticClassNoInline(); \
	UCookPlatformCommandlet::StaticClassNoInline(); \
	UMarkDLCMapsCommandlet::StaticClassNoInline(); \
	UMarkDemoMapsCommandlet::StaticClassNoInline(); \
	ULinearPackagesCommandlet::StaticClassNoInline(); \
	UApplyPatchCommandlet::StaticClassNoInline(); \
	UCreatePatchCommandlet::StaticClassNoInline(); \
	UMegaPackageCommandlet::StaticClassNoInline(); \
	UCutdownCommandlet::StaticClassNoInline(); \
	UCompileMatCommandlet::StaticClassNoInline(); \
	USMConvertCommandlet::StaticClassNoInline(); \
	UTestCommandlet::StaticClassNoInline(); \
	UMarkTexturesCommandlet::StaticClassNoInline(); \
	UDataRipCommandlet::StaticClassNoInline(); \
	UPackageFlagCommandlet::StaticClassNoInline(); \
	UCheckUnicodeCommandlet::StaticClassNoInline(); \
	UDuke220ConvertCommandlet::StaticClassNoInline(); \
	UConformCommandlet::StaticClassNoInline(); \
	UBuildSHACommandlet::StaticClassNoInline(); \
	UBuildPatchLocCommandlet::StaticClassNoInline(); \
	UBuildMP3HashCommandlet::StaticClassNoInline(); \
	UBrushBuilder::StaticClassNoInline(); \
	GNativeLookupFuncs[Lookup++] = &FindEditorUBrushBuilderNative; \
	UBatchExportCommandlet::StaticClassNoInline(); \
	UTrueTypeFontFactory::StaticClassNoInline(); \
	AEditorMesh::StaticClassNoInline(); \

#endif // NATIVE_DEFS_ONLY

#ifdef NATIVES_ONLY
#if _MSC_VER
#pragma message("*** Including native classes from Editor.")
#endif
NATIVE_INFO(UBrushBuilder) GEditorUBrushBuilderNatives[] = 
{ 
	MAP_NATIVE(UBrushBuilder,execPolyEnd)
	MAP_NATIVE(UBrushBuilder,execPolyi)
	MAP_NATIVE(UBrushBuilder,execPolyBegin)
	MAP_NATIVE(UBrushBuilder,execPoly4i)
	MAP_NATIVE(UBrushBuilder,execPoly3i)
	MAP_NATIVE(UBrushBuilder,execVertex3f)
	MAP_NATIVE(UBrushBuilder,execVertexv)
	MAP_NATIVE(UBrushBuilder,execBadParameters)
	MAP_NATIVE(UBrushBuilder,execGetPolyCount)
	MAP_NATIVE(UBrushBuilder,execGetVertex)
	MAP_NATIVE(UBrushBuilder,execGetVertexCount)
	MAP_NATIVE(UBrushBuilder,execEndBrush)
	MAP_NATIVE(UBrushBuilder,execBeginBrush)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(Editor,UBrushBuilder);

#endif // NATIVES_ONLY
#if _MSC_VER
#pragma warning(default:4121)
#endif

#ifdef VERIFY_CLASS_SIZES
#pragma message("*** Verifying class sizes for Editor.")
VERIFY_CLASS_SIZE_NODIE(UTextureCheckCommandlet)
VERIFY_CLASS_SIZE_NODIE(UStripGoreCommandlet)
VERIFY_CLASS_SIZE_NODIE(UStaticMeshFactory)
VERIFY_CLASS_SIZE_NODIE(USoundPackCommandlet)
VERIFY_CLASS_SIZE_NODIE(USoundCheckCommandlet)
VERIFY_CLASS_SIZE_NODIE(UOptimizeCommandlet)
VERIFY_CLASS_SIZE_NODIE(UBitMatrix)
VERIFY_CLASS_SIZE_NODIE(UBitArray)
VERIFY_CLASS_SIZE_NODIE(UTransactor)
VERIFY_CLASS_SIZE_NODIE(UTransBuffer)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshSmooth,OptionsStaticMeshSmooth,SmoothType)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshSmooth,OptionsStaticMeshSmooth,SmoothAngle)
VERIFY_CLASS_SIZE_NODIE(UOptionsStaticMeshSmooth)
VERIFY_CLASS_OFFSET_NODIE(UOptionsProxy,OptionsProxy,DlgCaption)
VERIFY_CLASS_OFFSET_NODIE(UOptionsProxy,OptionsProxy,WinWidth)
VERIFY_CLASS_OFFSET_NODIE(UOptionsProxy,OptionsProxy,WinHeight)
VERIFY_CLASS_SIZE_NODIE(UOptionsProxy)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,OverrideWidth)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,OverrideHeight)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,NumSmooths)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,NumExpands)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,TexturePkg)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,TextureGroup)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,NumSamples)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,SampleScale)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,SampleDist)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,SampleMode)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,SuperSample)
VERIFY_CLASS_OFFSET_NODIE(UOptionsStaticMeshNormalMap,OptionsStaticMeshNormalMap,BumpScale)
VERIFY_CLASS_SIZE_NODIE(UOptionsStaticMeshNormalMap)
VERIFY_CLASS_OFFSET_NODIE(UOptionsMatNewStaticMesh,OptionsMatNewStaticMesh,PkgName)
VERIFY_CLASS_OFFSET_NODIE(UOptionsMatNewStaticMesh,OptionsMatNewStaticMesh,Group)
VERIFY_CLASS_OFFSET_NODIE(UOptionsMatNewStaticMesh,OptionsMatNewStaticMesh,MeshName)
VERIFY_CLASS_OFFSET_NODIE(UOptionsMatNewStaticMesh,OptionsMatNewStaticMesh,MeshPitch)
VERIFY_CLASS_OFFSET_NODIE(UOptionsMatNewStaticMesh,OptionsMatNewStaticMesh,MeshYaw)
VERIFY_CLASS_OFFSET_NODIE(UOptionsMatNewStaticMesh,OptionsMatNewStaticMesh,MeshRoll)
VERIFY_CLASS_SIZE_NODIE(UOptionsMatNewStaticMesh)
VERIFY_CLASS_OFFSET_NODIE(UOptionsSurfBevel,OptionsSurfBevel,Depth)
VERIFY_CLASS_OFFSET_NODIE(UOptionsSurfBevel,OptionsSurfBevel,Bevel)
VERIFY_CLASS_SIZE_NODIE(UOptionsSurfBevel)
VERIFY_CLASS_OFFSET_NODIE(UOptions2DShaperBezierDetail,Options2DShaperBezierDetail,DetailLevel)
VERIFY_CLASS_SIZE_NODIE(UOptions2DShaperBezierDetail)
VERIFY_CLASS_OFFSET_NODIE(UOptions2DShaperRevolve,Options2DShaperRevolve,Per360)
VERIFY_CLASS_OFFSET_NODIE(UOptions2DShaperRevolve,Options2DShaperRevolve,Use)
VERIFY_CLASS_SIZE_NODIE(UOptions2DShaperRevolve)
VERIFY_CLASS_OFFSET_NODIE(UOptions2DShaper,Options2DShaper,Axis)
VERIFY_CLASS_SIZE_NODIE(UOptions2DShaper)
VERIFY_CLASS_SIZE_NODIE(UOptions2DShaperSheet)
VERIFY_CLASS_OFFSET_NODIE(UOptions2DShaperExtrudeToBevel,Options2DShaperExtrudeToBevel,Height)
VERIFY_CLASS_OFFSET_NODIE(UOptions2DShaperExtrudeToBevel,Options2DShaperExtrudeToBevel,CapHeight)
VERIFY_CLASS_SIZE_NODIE(UOptions2DShaperExtrudeToBevel)
VERIFY_CLASS_OFFSET_NODIE(UOptions2DShaperExtrudeToPoint,Options2DShaperExtrudeToPoint,Depth)
VERIFY_CLASS_SIZE_NODIE(UOptions2DShaperExtrudeToPoint)
VERIFY_CLASS_OFFSET_NODIE(UOptions2DShaperExtrude,Options2DShaperExtrude,Depth)
VERIFY_CLASS_SIZE_NODIE(UOptions2DShaperExtrude)
VERIFY_CLASS_OFFSET_NODIE(UOptionsTexAlignCylinder,OptionsTexAlignCylinder,UTile)
VERIFY_CLASS_OFFSET_NODIE(UOptionsTexAlignCylinder,OptionsTexAlignCylinder,VTile)
VERIFY_CLASS_SIZE_NODIE(UOptionsTexAlignCylinder)
VERIFY_CLASS_OFFSET_NODIE(UOptionsTexAlign,OptionsTexAlign,TAxis)
VERIFY_CLASS_SIZE_NODIE(UOptionsTexAlign)
VERIFY_CLASS_SIZE_NODIE(UOptionsTexAlignPlanar)
VERIFY_CLASS_OFFSET_NODIE(UOptionsTexAlignFace,OptionsTexAlignFace,TileU)
VERIFY_CLASS_OFFSET_NODIE(UOptionsTexAlignFace,OptionsTexAlignFace,TileV)
VERIFY_CLASS_SIZE_NODIE(UOptionsTexAlignFace)
VERIFY_CLASS_OFFSET_NODIE(UOptionsBrushScale,OptionsBrushScale,X)
VERIFY_CLASS_OFFSET_NODIE(UOptionsBrushScale,OptionsBrushScale,Y)
VERIFY_CLASS_OFFSET_NODIE(UOptionsBrushScale,OptionsBrushScale,Z)
VERIFY_CLASS_SIZE_NODIE(UOptionsBrushScale)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,NotifyVtbl)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,Level)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,TempModel)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,CurrentMaterial)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,CurrentClass)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,CurrentStaticMesh)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,EditorParticleSystems)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,Trans)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,Results)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,Pad)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,MenuUp)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,MenuDn)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,CollOn)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,CollOff)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,PlyrOn)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,PlyrOff)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,LiteOn)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,LiteOff)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,Bad)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,Bkgnd)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,BkgndHi)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,PatchEditMode)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,PatchPaintMode)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,PatchPaintRadiusInner)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,PatchPaintRadiusOuter)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,PatchPaintStrength)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,PatchPaintValue1)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,PatchPaintValue2)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,AutoSaveIndex)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,AutoSaveCount)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,Mode)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,ClickFlags)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,MovementSpeed)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,ParentContext)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,ClickLocation)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,ClickPlane)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,Tools)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,BrowseClass)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,GridCheckErrorThreshold)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,ConstraintsVtbl)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,UseSizingBox)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,SnapDistance)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,GridSize)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,RotGridSize)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,FovAngle)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,AutosaveTimeMinutes)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,GameCommandLine)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,EditPackages)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_View2DAxes)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_View2DBackground)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_View2DWires)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_View3DAxes)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_View3DBackground)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_View3DWires)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_ViewLightModeAxes)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_ViewLightModeBackground)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_ViewLightModeWires)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_BrushWorking)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_BrushAddWire)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_BrushSubtractWire)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_BrushSemiSolidWire)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_BrushNonSolidWire)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_BrushPortalWire)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_ActorInfoWire)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,C_BackgroundColor)
VERIFY_CLASS_OFFSET_NODIE(UEditorEngine,EditorEngine,LockMeshView)
VERIFY_CLASS_SIZE_NODIE(UEditorEngine)
VERIFY_CLASS_SIZE_NODIE(UFontFactory)
VERIFY_CLASS_SIZE_NODIE(UTextureFactory)
VERIFY_CLASS_SIZE_NODIE(UTextureExporterTXT)
VERIFY_CLASS_SIZE_NODIE(UTextureExporterTGA)
VERIFY_CLASS_SIZE_NODIE(UTextureExporterBMP)
VERIFY_CLASS_SIZE_NODIE(UTextureExporterPCX)
VERIFY_CLASS_SIZE_NODIE(UMusicFactory)
VERIFY_CLASS_SIZE_NODIE(USoundFactory)
VERIFY_CLASS_SIZE_NODIE(UModelFactory)
VERIFY_CLASS_SIZE_NODIE(UPolysFactory)
VERIFY_CLASS_SIZE_NODIE(ULevelFactory)
VERIFY_CLASS_SIZE_NODIE(UClassFactoryUC)
VERIFY_CLASS_OFFSET_NODIE(UTextureFactoryNew,TextureFactoryNew,VSize)
VERIFY_CLASS_OFFSET_NODIE(UTextureFactoryNew,TextureFactoryNew,USize)
VERIFY_CLASS_OFFSET_NODIE(UTextureFactoryNew,TextureFactoryNew,TextureClass)
VERIFY_CLASS_OFFSET_NODIE(UTextureFactoryNew,TextureFactoryNew,TexturePackage)
VERIFY_CLASS_OFFSET_NODIE(UTextureFactoryNew,TextureFactoryNew,TextureName)
VERIFY_CLASS_SIZE_NODIE(UTextureFactoryNew)
VERIFY_CLASS_OFFSET_NODIE(UClassFactoryNew,ClassFactoryNew,Superclass)
VERIFY_CLASS_OFFSET_NODIE(UClassFactoryNew,ClassFactoryNew,ClassPackage)
VERIFY_CLASS_OFFSET_NODIE(UClassFactoryNew,ClassFactoryNew,ClassName)
VERIFY_CLASS_SIZE_NODIE(UClassFactoryNew)
VERIFY_CLASS_OFFSET_NODIE(ULevelFactoryNew,LevelFactoryNew,Author)
VERIFY_CLASS_OFFSET_NODIE(ULevelFactoryNew,LevelFactoryNew,LevelTitle)
VERIFY_CLASS_SIZE_NODIE(ULevelFactoryNew)
VERIFY_CLASS_SIZE_NODIE(UClassExporterH)
VERIFY_CLASS_SIZE_NODIE(ULevelExporterDBD)
VERIFY_CLASS_SIZE_NODIE(ULevelExporterMA)
VERIFY_CLASS_SIZE_NODIE(ULevelExporterDXF)
VERIFY_CLASS_SIZE_NODIE(ULevelExporterSTL)
VERIFY_CLASS_SIZE_NODIE(ULevelExporterT3D)
VERIFY_CLASS_SIZE_NODIE(UModelExporterT3D)
VERIFY_CLASS_SIZE_NODIE(UPolysExporterT3D)
VERIFY_CLASS_SIZE_NODIE(UClassExporterUC)
VERIFY_CLASS_SIZE_NODIE(UClassExporterUCH)
VERIFY_CLASS_SIZE_NODIE(UMusicExporterTracker)
VERIFY_CLASS_SIZE_NODIE(USoundExporterWAV)
VERIFY_CLASS_SIZE_NODIE(UTextBufferExporterTXT)
VERIFY_CLASS_SIZE_NODIE(UMasterCommandlet)
VERIFY_CLASS_SIZE_NODIE(UMakeCommandlet)
VERIFY_CLASS_SIZE_NODIE(UKillUnrealCommandlet)
VERIFY_CLASS_SIZE_NODIE(UCoalesceLocCommandlet)
VERIFY_CLASS_SIZE_NODIE(UDumpIntCommandlet)
VERIFY_CLASS_SIZE_NODIE(UPrecacheIndexCommandlet)
VERIFY_CLASS_SIZE_NODIE(UMusicListCommandlet)
VERIFY_CLASS_SIZE_NODIE(UAnimationListCommandlet)
VERIFY_CLASS_SIZE_NODIE(USoundReferenceCommandlet)
VERIFY_CLASS_SIZE_NODIE(UObjectReferenceCommandlet)
VERIFY_CLASS_SIZE_NODIE(UCutdownContentCommandlet)
VERIFY_CLASS_SIZE_NODIE(UCookPlatformCommandlet)
VERIFY_CLASS_SIZE_NODIE(UMarkDLCMapsCommandlet)
VERIFY_CLASS_SIZE_NODIE(UMarkDemoMapsCommandlet)
VERIFY_CLASS_SIZE_NODIE(ULinearPackagesCommandlet)
VERIFY_CLASS_SIZE_NODIE(UApplyPatchCommandlet)
VERIFY_CLASS_SIZE_NODIE(UCreatePatchCommandlet)
VERIFY_CLASS_SIZE_NODIE(UMegaPackageCommandlet)
VERIFY_CLASS_SIZE_NODIE(UCutdownCommandlet)
VERIFY_CLASS_SIZE_NODIE(UCompileMatCommandlet)
VERIFY_CLASS_SIZE_NODIE(USMConvertCommandlet)
VERIFY_CLASS_SIZE_NODIE(UTestCommandlet)
VERIFY_CLASS_SIZE_NODIE(UMarkTexturesCommandlet)
VERIFY_CLASS_SIZE_NODIE(UDataRipCommandlet)
VERIFY_CLASS_SIZE_NODIE(UPackageFlagCommandlet)
VERIFY_CLASS_SIZE_NODIE(UCheckUnicodeCommandlet)
VERIFY_CLASS_SIZE_NODIE(UDuke220ConvertCommandlet)
VERIFY_CLASS_SIZE_NODIE(UConformCommandlet)
VERIFY_CLASS_SIZE_NODIE(UBuildSHACommandlet)
VERIFY_CLASS_SIZE_NODIE(UBuildPatchLocCommandlet)
VERIFY_CLASS_SIZE_NODIE(UBuildMP3HashCommandlet)
VERIFY_CLASS_OFFSET_NODIE(UBrushBuilder,BrushBuilder,BitmapFilename)
VERIFY_CLASS_OFFSET_NODIE(UBrushBuilder,BrushBuilder,ToolTip)
VERIFY_CLASS_OFFSET_NODIE(UBrushBuilder,BrushBuilder,Vertices)
VERIFY_CLASS_OFFSET_NODIE(UBrushBuilder,BrushBuilder,Polys)
VERIFY_CLASS_OFFSET_NODIE(UBrushBuilder,BrushBuilder,Group)
VERIFY_CLASS_SIZE_NODIE(UBrushBuilder)
VERIFY_CLASS_SIZE_NODIE(UBatchExportCommandlet)
VERIFY_CLASS_OFFSET_NODIE(UTrueTypeFontFactory,TrueTypeFontFactory,NumCharacters)
VERIFY_CLASS_OFFSET_NODIE(UTrueTypeFontFactory,TrueTypeFontFactory,VSize)
VERIFY_CLASS_OFFSET_NODIE(UTrueTypeFontFactory,TrueTypeFontFactory,USize)
VERIFY_CLASS_OFFSET_NODIE(UTrueTypeFontFactory,TrueTypeFontFactory,Alpha)
VERIFY_CLASS_OFFSET_NODIE(UTrueTypeFontFactory,TrueTypeFontFactory,FontSize)
VERIFY_CLASS_OFFSET_NODIE(UTrueTypeFontFactory,TrueTypeFontFactory,FontFile)
VERIFY_CLASS_SIZE_NODIE(UTrueTypeFontFactory)
VERIFY_CLASS_OFFSET_NODIE(AEditorMesh,EditorMesh,NumTextures)
VERIFY_CLASS_OFFSET_NODIE(AEditorMesh,EditorMesh,TextureMemoryUsage)
VERIFY_CLASS_SIZE_NODIE(AEditorMesh)
#endif // VERIFY_CLASS_SIZES
